version: "3.2"

services:
  sample-node:
    build:
      context: .
      dockerfile: dev/docker/Dockerfile
    command: npm run watch
    ports:
      - "3001:3001"
    networks:
      - sample-node-net
    volumes:
      - .:/var/app/sample-node-ts
      - /var/app/sample-node-ts/node_modules
    env_file:
      - .env # it will overwrite .env file content
    depends_on:
      - sample-node_postgres

  sample-node_postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: sample-node
    ports:
      - "5432:5432"
    networks:
      - sample-node-net
    volumes:
      - "sample-node-postgres-vol:/var/lib/postgres"

networks:
  sample-node-net:
    driver: bridge
volumes:
  sample-node-postgres-vol:
